#!/bin/bash

if [[ $1 == 'mac' ]]; then
    echo "Installing Pre-reqs with Brew"
    brew install minikube
    brew install helm
elif [[ $1 == 'ubuntu' ]]; then
    echo "Installing Pre-reqs with Aptitude"
    sudo snap install minikube --classic
    sudo snap install helm --classic
else
    echo "Please specify 'mac' or 'ubuntu' as an input parameter"
fi

minikube start
minikube addons enable ingress

# add helm charts
helm repo add concourse https://concourse-charts.storage.googleapis.com/
helm repo add jetstack https://charts.jetstack.io
helm repo update

kubectl apply --validate=false -f https://github.com/jetstack/cert-manager/releases/download/v0.14.1/cert-manager.crds.yaml
kubectl create namespace cert-manager

# helm install cert-manager
helm install \
  cert-manager jetstack/cert-manager \
  --namespace cert-manager \
  --version v0.14.1

# Create Secret and Issuer
kubectl apply -f k8s_objs/ca-secret.yaml
sleep 2
kubectl apply -f k8s_objs/issuer.yaml

# Install Concourse
helm install -f k8s_objs/values.yml control-plane concourse/concourse

# kubectl create secret generic github-key --from-literal=value="$(cat k8s_objs/secrets/github_key)"" -n concourse-main