---
resources:
  - name: platform-automation
    type: git
    source:
      branch: master
      uri: git@github.com:bcdurden/control_plane_paver.git
      private_key: ((creds.github-key))

  - name: tf-state
    type: s3
    source:
      bucket: pivotal-poc-bucket-1
      access_key_id: ((creds.aws-access-key))
      secret_access_key: ((creds.aws-secret-key))
      skip_ssl_verification: true
      region_name: us-east-2
      endpoint: ((s3_endpoint))
      versioned_file: tfstate
      initial_content_text: '{}'
      initial_version: 'empty-start'
jobs:
  - name: job
    public: true
    plan:
      - get: platform-automation
      - task: get-certs
        config:
          platform: linux
          image_resource:
            type: registry-image
            source: 
              repository: alpine
          inputs:
          - name: platform-automation
          params:
            TLS: ((tls-certificate))
          outputs:
            - name: tls-certificate
          run:
            path: sh
            args: ["platform-automation/custom_tasks/get_cert.sh"]

      - task: terraform-plan
        config:
          platform: linux
          image_resource:
            type: registry-image
            source: 
              repository: hashicorp/terraform
              tag: 0.11.14
          inputs:
          - name: platform-automation
          - name: tls-certificate
          params:
            AWS_ACCESS_KEY_ID: ((creds.aws-access-key))
            AWS_SECRET_ACCESS_KEY: ((creds.aws-secret-key))
            AWS_DEFAULT_REGION: us-east-2
          outputs:
          - name: terraform-output
          run:
            path: sh
            args: ["platform-automation/custom_tasks/terraform_init.sh"]
            
      - task: resource-task
        config:
          platform: linux
          image_resource:
            type: registry-image
            source: 
              repository: hashicorp/terraform
              tag: 0.11.14
          inputs:
            - name: platform-automation
            - name: terraform-output
          outputs:
          - name: terraform-output
          params:
            AWS_ACCESS_KEY_ID: ((creds.aws-access-key))
            AWS_SECRET_ACCESS_KEY: ((creds.aws-secret-key))
            AWS_DEFAULT_REGION: us-east-2
          run:
            path: sh
            args: ["platform-automation/custom_tasks/terraform_apply.sh"]