---
resources:
  - name: platform-automation
    type: git
    source:
      branch: master
      uri: git@github.com:bcdurden/control_plane_paver.git
      private_key: ((creds.github-key))
jobs:
  - name: job
    public: true
    plan:
      - get: platform-automation
      - task: terraform-plan
        config:
          platform: linux
          image_resource:
            type: registry-image
            source: 
              repository: hashicorp/terraform
              tag: 0.11.14
          inputs:
          - name: platform-automation
          outputs:
          - name: terraform-output
          run:
            path: sh
            args: ["platform-automation/custom_tasks/terraform_init.sh"]
      - task: resource-task
        config:
          platform: linux
          image_resource:
            type: registry-image
            source: 
              repository: hashicorp/terraform
              tag: 0.11.14
          inputs:
            - name: platform-automation
            - name: terraform-output
          outputs:
          - name: terraform-output
          params:
            AWS_ACCESS_KEY_ID: ((creds.aws-access-key))
            AWS_SECRET_ACCESS_KEY: ((creds.aws-secret-key))
            AWS_DEFAULT_REGION: us-east-2
          run:
            path: sh
            args: ["platform-automation/custom_tasks/terraform_plan.sh"]