s3_region_name: us-east-2
s3_pivnet_products_bucket: piv-poc-bucket-1
wcf_root_cert: |
  -----BEGIN CERTIFICATE-----
  MIIDNTCCAh2gAwIBAgIJAMc3B7K5HeWyMA0GCSqGSIb3DQEBCwUAMBYxFDASBgNV
  BAMMC0Vhc3ktUlNBIENBMB4XDTIwMDQwOTEzMDY0N1oXDTMwMDQwNzEzMDY0N1ow
  FjEUMBIGA1UEAwwLRWFzeS1SU0EgQ0EwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAw
  ggEKAoIBAQDPM6ZRJFpNQ6LdBhZDtgEoqOVHINKaztZpwlqrSnylOWSlGPEQOLwj
  i+6F4BnXrUdSfi5r4wUarerSshSjBzkNL6HIWGxwg7pvxzMEQ2BU7b/ZZZqwZuFw
  6lLwX2+G9/ziy87E0nGxVJjvj2lL0HM2oEDrza0y8elZPj1KI3Sg1V1fPko7AVN9
  FLTVeLHZjHlM7F8PoXeg7xOOhd2zK9rWIPmIsKIvnb9yAfE0b90BJKT5CE1YMnN0
  /vB9gPWmo5TugS4SYUohk6KDjKRxcns8HjH2q3TMlekWENDqBEoGBemJLtSp5pm+
  XskQIwhTh1o4TcGfX94ZcYiJZqPGl7ZXAgMBAAGjgYUwgYIwHQYDVR0OBBYEFOFy
  ew9BJnN/9ZO+bVrxGzbTNJ4AMEYGA1UdIwQ/MD2AFOFyew9BJnN/9ZO+bVrxGzbT
  NJ4AoRqkGDAWMRQwEgYDVQQDDAtFYXN5LVJTQSBDQYIJAMc3B7K5HeWyMAwGA1Ud
  EwQFMAMBAf8wCwYDVR0PBAQDAgEGMA0GCSqGSIb3DQEBCwUAA4IBAQAVwbU4U12L
  U/yDspeyFU0ir6my4IHiijES8bYRz+FBi48jMRJJiFAHYM3lKAiDgKcq1i5jG2EA
  7+s7e7df43DQwrS9RqIznnd/no3/0ke0jcF15RmkF9Arg5SjKCqkHWyMjjcfn43u
  HfWpz2HfJLY9KoAO2LTp6/AKG5y0lG6qXG6l6EL299ryvaocPXhP5Wi/1lXncm81
  EEBYacZtjaXM1Pdx1IYH88Mcog29Rp/7GDaQ5YR6OLSWzQOiSSBQkgdAhIPoCPPR
  HBmWeiNTz1v1VMkbU9f4loGSj2RfgQTuYlhZ7aLX9fl+23NjYDz9K535wBlM5//G
  dUSIdTOhXxqF
  -----END CERTIFICATE-----
